### ISSUE TITLE
New equipment bug

### ISSUE THREAD

**Issue by KyoriAsh** [Yuubari/KanColleViewer#39] opened 2015-02-08 03:08 UTC
WG42's stat unable to display correctly. Armor -1 display as Attack Rng (1)

**Comment by Yuubari** [comment] 2015-02-09 21:57
Not a bug. WG42 has short attack range (= 1). KCV does not display armour decrease at the moment.

**Comment by Yuubari** [comment] 2015-02-09 22:31
Fixed in 3daff39508089202093944645843ff6b3233dc6c.

**Closed by Yuubari** 2015-02-09 22:31 UTC
