### ISSUE TITLE
Tone Kai 2 repair time error

### ISSUE THREAD

**Issue by NicolaosGreene** [Yuubari/KanColleViewer#58] opened 2015-05-10 21:04 UTC
When I hover over the health bar of Tone Kai 2 and it gives me a repair time it is significantly different than the time the dock tells me. At level 74 and 36/59 health the UI in KCV claims 3:08:20 vs the dock saying 4:42:15. I don't know if this is due to her being mislabeled as a CA rather than a CAV since I recall seeing a discrepancy when I was repairing Mogami Kai as well. Anyways thanks for your time. Version is 3.7.0 Rev 3

**Comment by Yuubari** [comment] 2015-05-27 09:47
Can you elaborate on “being mislabelled as a CA”? Repair time is normally calculated based on the values presented by the API, and Tone Kai Ni is most certainly a CAV according to the API. Where exactly is she mislabelled so?

**Comment by Yuubari** [comment] 2015-05-27 09:54
Also, judging by the repair formula, the problem is with the ship type multiplier (CA and CAV have the exact same multiplier). I'll look into this later.

**Comment by Yuubari** [comment] 2015-05-27 10:18
Fixed in 0670a08d144e588be8a8927452d14b019fe13e10.

**Closed by Yuubari** 2015-05-27 10:18 UTC
